[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_transfer_project = "CqNc5xHcA9HLQAMEyWKudapC6Comf1PksQRJJVrjPNbL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/phantom/rust/new-token/rgbdAtmtqGH87AR6XTZyunnjiJuAHGxk1Ex4Ajp8zCa.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
